//Generated by AIOCodeGen do not edit!
#import "FlutterServiceTemplate.h"

 @interface Service_DemoService : NSObject
 + (FlutterServiceTemplate *)service;
 + (void)MessageToFlutter:(void (^)(NSDictionary *))resultCallback message:(NSString *)message ;
 @end
